### PR TITLE
Add goreleaser configuration for AUR

### PR DESCRIPTION
**Pull request by jneidel**
Setup goreleaser up to create releases for the AUR.

To get this ready on your end you need to:
- [create an account in the AUR](https://aur.archlinux.org/)
- generate a new ssh keypair (w/o password)
- set the AUR up to use your that new key pair
- add the private key where ever goreleaser can get it through this: `'{{ .Env.AUR_KEY }}'` 

[Ref: docs](https://goreleaser.com/customization/aur)

Ping me and I'll test if the package installs as expected :smile:

### CODE REVIEW

**Comment by Yakitrak** [comment]
I will updating the goreleaser soon to run tests before releasing so will do this change as part of it. Thank you for the suggestion and feedback!

**Comment by Yakitrak** [comment]
I just realised I can also add it to chocolaty for Windows too which would complete #15.

**Comment by Yakitrak** [comment]
@jneidel as part of account creation, I need to provide the output for `LC_ALL=C pacman -V|sed -r 's#[0-9]+#903#g'|md5sum|cut -c1-6` but I don't have access to Arch Linux so can't run this - would you be able to help me with the account creation please? Or if you're happy to I can let you use your account on this if that's safe for you?

**Comment by jneidel** [comment]
> LC_ALL=C pacman -V|sed -r 's#[0-9]+#903#g'|md5sum|cut -c1-6

fa3139 :)

**Comment by Yakitrak** [comment]
> fa3139 :)

Thank you but The calculation is different everytime, I believe it serves as a captcha. For example now when I am trying, its asking for `LC_ALL=C pacman -V|sed -r 's#[0-9]+#539#g'|md5sum|cut -c1-6`.

If you want, please feel free to add your account as even if I manage to register, if there any issues on this, I'd have no way to debug :)

**Comment by jneidel** [comment]
> it serves as a captcha

Yes and very effectively at that :)

I will be a maintaining the package, but you need a private key of your own to be able to publish.

Email me the captcha to `aur@jneidel.com`, then I can get back to you faster, so you can get your account created :)

**Comment by jneidel** [comment]
Actually, I could just create an account for you and pass you the credentials :smile:

**Comment by Yakitrak** [comment]
@jneidel yes please, that would be great. Sorry I've been been busy so haven't been active on this repo but happy to merge this PR if you can arrange credentials.

**Comment by jneidel** [comment]
Let's do that.
Where can I email you the credentials?

**Comment by Yakitrak** [comment]
Please use the same email as you listed on the maintainers section of PR

**Review by Yakitrak — APPROVED** [review]
Thank you @jneidel

**Pull request merged**
